### PR TITLE
feat: Adding submitJob function and types

### PR DESCRIPTION
**Pull request by AtelyPham**
### Summary of changes

- Added the `submitJob` function along with a simple test case.
- Included the types of jobs and roles.
- Properly configured the @webb-tools/tangle-substrate-types with the SDK.

### CODE REVIEW

**Comment by AtelyPham** [comment]
There are still two issues on the pull request that need to be addressed before it is ready for review:

1. The `tangle-substrate-types` package needs to be published with the fixes from PR https://github.com/webb-tools/tangle/pull/572. Currently, it is using the local package.
2. There is a testing error with `jest`: `Jest has detected the following 1 open handle potentially preventing Jest from exiting.`

CleanShot 2024-03-21 at 20 39 14@2x

**Comment by salman01zp** [comment]
https://github.com/webb-tools/relayer/blob/main/tests/lib/substrateNodeBase.ts
This might help you seting up a local node for testing.

**Comment by AtelyPham** [comment]
> [webb-tools/relayer@`main`/tests/lib/substrateNodeBase.ts](https://github.com/webb-tools/relayer/blob/main/tests/lib/substrateNodeBase.ts?rgh-link-date=2024-03-21T14%3A36%3A03Z) This might help you seting up a local node for testing.

Thanks 🙏 I'll handle this on a separate PR.

**Comment by salman01zp** [comment]
I opened up PR for setting up the Local test node. I ran into some Esm loader issues and need some fixing
Maybe you can merge that into this PR and update your tests

https://github.com/webb-tools/tangle-mpc-sdk/pull/8

**Comment by drewstone** [comment]
@salman01zp can you fix up the merge conflicts in these PRs so we can merge. I merged your PR in first and it led to this.

**Comment by AtelyPham** [comment]
> @salman01zp can you fix up the merge conflicts in these PRs so we can merge. I merged your PR in first and it led to this.

I'll give it a shot 👀

**Pull request merged**
